# Generated by Django 4.1 on 2022-08-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('codice', models.CharField(max_length=100, null=True, unique=True)),
                ('category', models.CharField(choices=[('D900', 'D900'), ('CS2100', 'CS2100'), ('CS2200', 'CS2200')], max_length=10, null=True)),
                ('quantita', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
