# Generated by Django 4.1 on 2022-08-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Prodotti scaricati'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Prodotti'},
        ),
    ]
